kind: project
metadata:
  name: berkeley-mlops
  created: '2022-09-06T16:57:10.214000+00:00'
spec:
  functions:
  - url: functions/get_data.py
    name: get-data
    kind: job
    image: mlrun/mlrun
  - url: functions/train.py
    name: train-model
    kind: job
    image: mlrun/mlrun
  - url: hub://v2_model_server
    name: deploy-model
  workflows:
  - name: train
    path: pipelines/training_pipeline.py
    engine: null
  artifacts: []
  source: ''
  desired_state: online
  owner: nick
status:
  state: online
